# Generated by Django 5.0.6 on 2024-07-17 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('information_address', models.TextField(blank=True, null=True)),
                ('copyright_owner', models.CharField(choices=[('自有', '自有'), ('共有', '共有'), ('他人', '他人')], default='自有', max_length=10)),
                ('dir_name', models.CharField(blank=True, max_length=255, null=True)),
                ('special_name', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, choices=[('春', '春'), ('夏', '夏'), ('秋', '秋'), ('冬', '冬')], max_length=2, null=True)),
                ('video_class', models.CharField(blank=True, choices=[('航拍', '航拍'), ('地拍', '地拍'), ('地拍+航拍', '地拍+航拍'), ('棚拍', '棚拍'), ('延时', '延时'), ('特殊摄影', '特殊摄影')], max_length=10, null=True)),
                ('picture_frame', models.CharField(blank=True, choices=[('横屏', '横屏'), ('竖屏', '竖屏')], max_length=2, null=True)),
                ('cultural_agri_product_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cultural_level1', to='CoreApp.culturalagriproduct')),
                ('cultural_agri_product_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cultural_level2', to='CoreApp.culturalagriproduct')),
                ('cultural_delicacies_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cultural_level1', to='CoreApp.culturaldelicacies')),
                ('cultural_delicacies_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cultural_level2', to='CoreApp.culturaldelicacies')),
                ('cultural_processed_product_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cultural_level1', to='CoreApp.culturalprocessedproduct')),
                ('cultural_processed_product_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cultural_level2', to='CoreApp.culturalprocessedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VideoHumanistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('information_address', models.TextField(blank=True, null=True)),
                ('copyright_owner', models.CharField(choices=[('自有', '自有'), ('共有', '共有'), ('他人', '他人')], default='自有', max_length=10)),
                ('dir_name', models.CharField(blank=True, max_length=255, null=True)),
                ('special_name', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, choices=[('春', '春'), ('夏', '夏'), ('秋', '秋'), ('冬', '冬')], max_length=2, null=True)),
                ('video_class', models.CharField(blank=True, choices=[('航拍', '航拍'), ('地拍', '地拍'), ('地拍+航拍', '地拍+航拍'), ('棚拍', '棚拍'), ('延时', '延时'), ('特殊摄影', '特殊摄影')], max_length=10, null=True)),
                ('picture_frame', models.CharField(blank=True, choices=[('横屏', '横屏'), ('竖屏', '竖屏')], max_length=2, null=True)),
                ('humanistic_category_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_humanistic_level1', to='CoreApp.humanisticcategory')),
                ('humanistic_category_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_humanistic_level2', to='CoreApp.humanisticcategory')),
                ('humanistic_heritage_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_humanistic_level1', to='CoreApp.humanisticheritage')),
                ('humanistic_heritage_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_humanistic_level2', to='CoreApp.humanisticheritage')),
                ('humanistic_topic_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_humanistic_level1', to='CoreApp.humanistictopic')),
                ('humanistic_topic_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_humanistic_level2', to='CoreApp.humanistictopic')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('information_address', models.TextField(blank=True, null=True)),
                ('copyright_owner', models.CharField(choices=[('自有', '自有'), ('共有', '共有'), ('他人', '他人')], default='自有', max_length=10)),
                ('dir_name', models.CharField(blank=True, max_length=255, null=True)),
                ('special_name', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, choices=[('春', '春'), ('夏', '夏'), ('秋', '秋'), ('冬', '冬')], max_length=2, null=True)),
                ('video_class', models.CharField(blank=True, choices=[('航拍', '航拍'), ('地拍', '地拍'), ('地拍+航拍', '地拍+航拍'), ('棚拍', '棚拍'), ('延时', '延时'), ('特殊摄影', '特殊摄影')], max_length=10, null=True)),
                ('picture_frame', models.CharField(blank=True, choices=[('横屏', '横屏'), ('竖屏', '竖屏')], max_length=2, null=True)),
                ('place_humanistic_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level1', to='CoreApp.placehumanistic')),
                ('place_humanistic_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level2', to='CoreApp.placehumanistic')),
                ('place_humanistic_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level3', to='CoreApp.placehumanistic')),
                ('place_location_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level1', to='CoreApp.placelocation')),
                ('place_location_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level2', to='CoreApp.placelocation')),
                ('place_location_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level3', to='CoreApp.placelocation')),
                ('place_natural_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level1', to='CoreApp.placenatural')),
                ('place_natural_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level2', to='CoreApp.placenatural')),
                ('place_natural_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_places_level3', to='CoreApp.placenatural')),
            ],
        ),
    ]
